In [1]:
import tensorflow as tf
from numpy.random import RandomState

/Library/Python/2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
batch_size = 8

In [3]:
W1 = tf.Variable(tf.random_normal([2,3], stddev=1, seed=1))
W2 = tf.Variable(tf.random_normal([3,1], stddev=1, seed=1))

In [4]:
x = tf.placeholder(tf.float32, shape=(None, 2), name = 'x-input') # (None, 2)
y_ = tf.placeholder(tf.float32, shape=(None, 1), name = 'y-input') # (None, 1) label

In [5]:
a=tf.matmul(x, W1) #(None, 3)
y=tf.matmul(a, W2) #(None, 1)
y=tf.sigmoid(y) # (None, 1)
# 计算交叉熵
cross_entrophy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)) + (1-y_)* tf.log(tf.clip_by_value(1-y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entrophy)

In [6]:
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

In [7]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print sess.run(W1)
    print sess.run(W2)
    STEPS = 5000
    for i in range(50000):
        start = (i * batch_size) % dataset_size
        end = min(start + batch_size, dataset_size)
        sess.run(train_step, feed_dict = {x: X, y_: Y})
        
        if i % 1000 == 0:
            entrophy = sess.run(cross_entrophy, feed_dict = {x: X, y_: Y})
            print("After %d steps cross_entrophy is %f" % (i, entrophy))

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 steps cross_entrophy is 1.898049
After 1000 steps cross_entrophy is 0.642042
After 2000 steps cross_entrophy is 0.616937
After 3000 steps cross_entrophy is 0.608774
After 4000 steps cross_entrophy is 0.608085
After 5000 steps cross_entrophy is 0.608079
After 6000 steps cross_entrophy is 0.608079
After 7000 steps cross_entrophy is 0.608079
After 8000 steps cross_entrophy is 0.608079
After 9000 steps cross_entrophy is 0.608079
After 10000 steps cross_entrophy is 0.608079
After 11000 steps cross_entrophy is 0.608079
After 12000 steps cross_entrophy is 0.608079
After 13000 steps cross_entrophy is 0.608079
After 14000 steps cross_entrophy is 0.608079
After 15000 steps cross_entrophy is 0.608079
After 16000 steps cross_entrophy is 0.608079
After 17000 steps cross_entrophy is 0.608079
After 18000 steps cross_entrophy is 0.608079
After 19000 steps cross_entrophy 

In [8]:
with tf.Session() as sess:
    v = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
    print tf.clip_by_value(v, 2.5, 4.5).eval()
    print sess.run(tf.square(v))
    print sess.run(tf.reduce_mean(tf.square(v)))

[[2.5 2.5 3. ]
 [4.  4.5 4.5]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
15.166667
